apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bind
  template:
    metadata:
      labels:
        app: bind
    spec:
      containers:
      - name: bind
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/bind
        command: ["/bin/bash", "-c"]
        args:
          - |
            /usr/local/bin/zone_converter.py /etc/bind/records.yaml /etc/bind/zones/{{ .Values.dns.zoneName }}.zone && \
            named -g -c /etc/bind/named.conf
      volumes:
      - name: config
        configMap:
          name: bind-records
