apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind-flask
  template:
    metadata:
      labels:
        app: bind-flask
    spec:
      containers:
        - name: bind-flask
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: {{ .Values.service.apiPort }}
              protocol: TCP
          env:
            - name: BIND_ZONE
              value: "{{ .Values.env.BIND_ZONE }}"
            - name: BIND_NS_IP
              value: "{{ .Values.env.BIND_NS_IP }}"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: bind-secrets
                  key: apiKey
          volumeMounts:
            - name: records
              mountPath: /data/records.yaml
              subPath: records.yaml
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.apiPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.apiPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: records
          persistentVolumeClaim:
            claimName: bind-records-pvc
