apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind
  namespace: bind-flask
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bind
  template:
    metadata:
      labels:
        app: bind
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
      - name: bind
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/bind
        - name: zones
          mountPath: /etc/bind/zones
        command: ["/bin/bash", "-c"]
        args:
          - |
            mkdir -p /etc/bind/zones && \
            /usr/local/bin/zone_converter.py /etc/bind/records.yaml /etc/bind/zones/{{ .Values.dns.zoneName }}.zone && \
            named -g -c /etc/bind/named.conf
      volumes:
      - name: config
        configMap:
          name: bind-records
      - name: zones
        emptyDir: {}
