apiVersion: v1
kind: Service
metadata:
  name: bind-flask
spec:
  type: {{ .Values.service.type }}
  selector:
    app: bind-flask
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: api
      port: {{ .Values.service.apiPort }}
      protocol: TCP
      targetPort: {{ .Values.service.apiPort }}
