name: Build and Deploy

on:
  workflow_run:
    workflows:
      - Chaos Tests
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t 856817629634.dkr.ecr.us-west-2.amazonaws.com/bind-flask:latest .
          docker push 856817629634.dkr.ecr.us-west-2.amazonaws.com/bind-flask:latest

      - name: Package Helm chart
        run: |
          helm package ./bind-flask --destination ./charts

      - name: Deploy to production
        run: |
          helm upgrade --install bind-flask ./charts/bind-flask-latest.tgz