name: Chaos Tests

on:
  workflow_run:
    workflows:
      - Integration Tests
    types:
      - completed

jobs:
  chaos-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run chaos tests
        run: |
          chaos run chaos-experiments/