name: Docker Image CI

on:
  push:
    branches:
      - main 

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
      issues: write
    env:
      # AWS_REGION: us-west-2
      CHART_DIR: bind-flask/
      CHART_NAME: bind-flask
      ECR_REGISTRY: 856817629634.dkr.ecr.us-west-2.amazonaws.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::856817629634:role/github-oidc-template-Role-1Y4H3rYHKYvg
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: kcarterlabs/bind
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

          # Tag and push as latest
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Package Helm chart
        run: |
          helm package $CHART_DIR --destination .

      # - name: Push Helm chart to ECR
      #   run: |
      #     CHART_FILE=$(ls $CHART_NAME-*.tgz)
      #     helm push $CHART_FILE oci://$ECR_REPO

      - name: Push Helm chart to ECR
        run: |
          CHART_FILE=$(ls $CHART_NAME-*.tgz)
          helm push $CHART_FILE oci://$ECR_REGISTRY
