name: Build and Push Helm Chart to AWS ECR (OIDC)

on:
  push:
    branches: [main]
    paths:
      - 'bind-flask/**'

jobs:
  helm-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      CHART_DIR: bind-flask/
      CHART_NAME: bind-dns
      # ECR_REPO: 856817629634dkr.ecr.us-east-1.amazonaws.com/mychart

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::856817629634:role/github-oidc-template-Role-1Y4H3rYHKYvg
          aws-region: us-west-2

      # - name: Login to Amazon ECR (OCI for Helm)
      #   run: |
      #     aws ecr get-login-password --region $AWS_REGION | \
      #     helm registry login --username AWS --password-stdin $ECR_REPO

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Package Helm chart
        run: |
          helm package $CHART_DIR --destination .

      - name: Push Helm chart to ECR
        run: |
          CHART_FILE=$(ls $CHART_NAME-*.tgz)
          helm push $CHART_FILE oci://$ECR_REPO
