name: Integration Tests

on:
  workflow_run:
    workflows:
      - Unit Tests
    types:
      - completed

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to test environment
        run: |
          helm upgrade --install bind-flask ./bind-flask --values ./bind-flask/values.yaml

      - name: Run integration tests
        run: |
          pytest integration_tests/ --junitxml=integration-test-results.xml